// Objective-C API for talking to github.com/yggdrasil-network/yggdrasil-extras/src/mobile Go package.
//   gobind -lang=objc github.com/yggdrasil-network/yggdrasil-extras/src/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Dummy.objc.h"
#include "Config.objc.h"
#include "Yggdrasil.objc.h"

@class MobileMobileLogger;
@class MobileYggdrasil;

@interface MobileMobileLogger : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Yggdrasil mobile package is meant to "plug the gap" for mobile support, as
Gomobile will not create headers for Swift/Obj-C etc if they have complex
(non-native) types. Therefore for iOS we will expose some nice simple
functions. Note that in the case of iOS we handle reading/writing to/from TUN
in Swift therefore we use the "dummy" TUN interface instead.
 */
@interface MobileYggdrasil : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * GetAddressString gets the node's IPv6 address
 */
- (NSString* _Nonnull)getAddressString;
/**
 * GetBoxPubKeyString gets the node's public encryption key
 */
- (NSString* _Nonnull)getBoxPubKeyString;
- (NSString* _Nonnull)getCoordsString;
- (NSString* _Nonnull)getPeersJSON;
/**
 * GetSigPubKeyString gets the node's public signing key
 */
- (NSString* _Nonnull)getSigPubKeyString;
/**
 * GetSubnetString gets the node's IPv6 subnet in CIDR notation
 */
- (NSString* _Nonnull)getSubnetString;
- (NSString* _Nonnull)getSwitchPeersJSON;
/**
 * StartAutoconfigure starts a node with a randomly generated config
 */
- (DummyConduitEndpoint* _Nullable)startAutoconfigure:(NSError* _Nullable* _Nullable)error;
/**
 * StartJSON starts a node with the given JSON config. You can get JSON config
(rather than HJSON) by using the GenerateConfigJSON() function
 */
- (DummyConduitEndpoint* _Nullable)startJSON:(NSData* _Nullable)configjson error:(NSError* _Nullable* _Nullable)error;
/**
 * Stop the mobile Yggdrasil instance
 */
- (BOOL)stop:(NSError* _Nullable* _Nullable)error;
@end

/**
 * GenerateConfigJSON generates mobile-friendly configuration in JSON format
 */
FOUNDATION_EXPORT NSData* _Nullable MobileGenerateConfigJSON(void);

#endif
